development: &
  adapter: mysql2
  username: root
  password: 
  encoding: utf8
  host: localhost
  database: tiny_mon_production

production:
  <<: *MYSQL_DB

test: &TEST
  adapter: mysql2
  username: root
  password: 
  encoding: utf8
  host: localhost
  database: tiny_mon_test

cucumber:

  <<: *TEST
