email_domain: gmail.com
email_address: smtp.gmail.com
email_port: 587
email_user_name: jan.renz@gmail.com
email_password: **********
email_authentication: :login
email_sender_address: jan.renz@gmail.com
email_openssl_verify_mode: none
email_enable_starttls_auto: true
config:
  action_mailer:
    perform_deliveries: true
    raise_delivery_errors: true
host: "localhost:8199"
language: de

exception_recipients: tiny_mon@tinymon.org
exception_sender_address: '"Application Error" <error@tinymon.org>'

secret_token: '7e024c1ed9faf287539a1c113b60c2275bd83a11376a8951b6f7e242b85c646764e1783ec2aef7a32f5e7cd68b13fdf8eb4a126d793f9b41ccbddb761587bdf8'
secret_key_base: 'c56e7ab6fd21d22c0d4fc8900b8b79ab5b28befb70ccfb01e422953ae6fe6bab4580e23f9add2ed23ea3296f358e243203d59395403fcd463389b852961bd2c0'
