- language:
    name:
      en: "Language for notifications"
      de: "Sprache für Benachrichtigungen"
    type: String
    default: en
    values:
      English: en
      Deutsch: de
    description:
      en: "The language used for notifications. To change the language of the user interface, use language switcher in the page's header."
      de: "Die Sprache für Benachrichtigungen. Um die Sprache der Seite zu ändern, benutzen Sie bitte die Landessymbole in der Kopfzeile."
- email_enabled:
    name:
      en: "Email notifications enabled"
      de: "E-Mail-Benachrichtigungen aktivieren"
    description:
      en: "Whether or not email notifications on check run failures are delivered to you."
      de: "Gibt an, ob Benachrichtigungen über fehlgeschlagene Funktionstests per E-Mail an Sie geschickt werden."
    type: Boolean
    default: true
- broadcasts_enabled:
    name:
      en: "Broadcast e-mail news enabled"
      de: "E-Mail-Neuigkeiten aktivieren"
    description:
      en: "Whether or not broadcast email news by the site administrator are delivered to you."
      de: "Gibt an, ob Neuigkeiten des Administrators per E-Mail an Sie geschickt werden."
    type: Boolean
    default: true
- prowl_enabled:
    name:
      en: "Prowl enabled"
      de: "Prowl aktivieren"
    description:
      en: "Whether or not Prowl notifications on check run failures are delivered to your iPhone."
      de: "Gibt an, ob Benachrichtigungen über fehlgeschlagene Funktionstests mittels Prowl an Ihr iPhone geschickt werden."
    type: Boolean
- prowl_api_key:
    name:
      en: "Prowl API Key"
      de: "Prowl API-Key"
    description:
      en: "Your Prowl API key. Log in to your Prowl account to generate an API key."
      de: "Ihr Prowl API-Key. Besuchen Sie Ihr Prowl-Konto um einen API-Key zu generieren."
    type: String
- notify_comments:
    name:
      en: "Notify me of comments"
      de: "Mich über Kommentare benachrichtigen"
    description:
      en: "Whether or not to send an email to you, when someone posts a comment to a check run"
      de: "Gibt an, ob eine E-Mail an Sie geschickt werden soll, wenn jemand einen Testlauf kommentiert"
    type: Boolean
    default: true
- send_daily_stats:
    name:
      en: "Send me a daily stat"
      de: "Mir eine tägliche Statistikmail senden"
    description:
      en: "Whether or not to send an daily statistic email to youn"
      de: "Gibt an, ob täglich eine E-Mail mit einer kumulierten Statistik an Sie geschickt werden soll"
    type: Boolean
    default: false
